name: Deploy to ECS

on:
  workflow_call:
#   push:
#     branches:
#       - master 

jobs:
  deploy_to_ecs:
    name: Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service --cluster sampleCluster --service SampleClusterService --force-new-deployment
