name: CD

on:
#   push:
#     branches:
#       - dev
    workflow_call:
    workflow_dispatch:
      inputs:
        username:
          description: "Username"
          type: string
          required: true
          default: "jyothiswaroopreddy08"

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  
          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ inputs.username }}
        env:
            password: ${{ secrets.DOCKER_PASSWORD }}
            
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jyothiswaroopreddy08/python-sample:latest

        
         
