name: First Workflow

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Approval
        id: approval
        uses: repo/name-of-approval-action@v1
        with:
          email: jyothiswaroopreddy08@gmail.com
          subject: Manual Approval needed
          body: Review the test results and provide approval
