name: Main Workflow

on:
  workflow_call:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          cd src
          coverage run test_app.py
          coverage xml test_app.py
          coverage report test_app.py 
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
           
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
        
      - name: Build docker image
        run: |
          docker build . --file Dockerfile --tag my-app:latest          

      - name: Tag Docker image
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
         aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 157352102889.dkr.ecr.us-east-1.amazonaws.com
         docker tag my-app:latest 157352102889.dkr.ecr.us-east-1.amazonaws.com/sample-pyapp:latest

      - name: Push Docker image to ECR
        run: docker push 157352102889.dkr.ecr.us-east-1.amazonaws.com/sample-pyapp:latest
          
    
  
