name: Python Test

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: pip install pytest
          
      - name: Run Python script
        run: |
          cd src
          #python app.py
          make run
        
      - name: Run Test
        run: |
          cd src
          #pytest test_app.py
          make pytest
