name: Python Workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  dependencies:
    name: Install Dependencies
    uses: ./.github/workflows/CI.yml
        
  test:
    name: Run Tests
    needs: dependencies
    uses: ./.github/workflows/python-test.yml
    with:
      test-goal: 'pytest test_app.py'
    
  code-quality-scan:
    name: SonarQube scan
    needs: test
    uses: ./.github/workflows/sonar-scan.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

