name: Python Workflow

on:
#   workflow_call:
  workflow_dispatch:

jobs:
  dependencies:
    name: Install Dependencies
    uses: ./.github/workflows/CI.yml
        
  test:
    name: Run Tests
    needs: dependencies
    uses: ./.github/workflows/python-test.yml
    
  code-quality-scan:
    name: SonarQube scan
    needs: test
    uses: ./.github/workflows/sonar-scan.yml
