name: Python Workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: CI workflow
        uses: ./.github/workflows/CI/CIPython.yml
        

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: CD workflow
        uses: ./.github/workflows/CD/CDPython.yml
