name: Build-Docker-Image

on:
#   push:
#     branches:
#       - main
    workflow_call:
    workflow_dispatch:
     inputs:
      username:
         description: "Username"
         type: string
         required: true
         default: "jyothiswaroopreddy08"
      password:
         description: "Password"
         type: string
         required: true
         default: "ammusiri99@S"

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
        
      - name: Build docker image
        run: |
          docker build . --file Dockerfile --tag python-sample:latest     
          
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

      - name: Push Docker image to Dockerhub
        run: docker push python-sample:latest

        
         
