name: Python Workflow

on:
#   workflow_call:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/CI.yml
        
  cd:
#     name: CD
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: CD 
        uses: ./.github/workflows/CD.yml
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
