name: testing approval

on:
  workflow_dispatch:

jobs:
 dev:
    name: Provision Dev
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt
