name: Build-Docker-Image

on:
#   push:
#     branches:
#       - main
    workflow_call:
    workflow_dispatch:
     inputs:
      username:
         description: "Username"
         type: string
         required: true
         default: "jyothiswaroopreddy08"
      password:
         description: "Password"
         type: string
         required: true
         default: "ammusiri99@S"

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  
          
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jyothiswaroopreddy08/python-sample:latest

        
         
